# Generated by Django 3.2.7 on 2021-09-27 16:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awarded', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='image',
            field=cloudinary.models.CloudinaryField(default='x.png', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='awarded.users'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.TextField(),
        ),
    ]
