# Generated by Django 3.2.7 on 2021-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awarded', '0006_auto_20210928_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='created_date',
            field=models.DateTimeField(default='2021-09-28 07:35:35.15346+03'),
        ),
    ]
