# Generated by Django 3.2.7 on 2021-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awarded', '0007_award_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
